### ISSUE TITLE
How can I assign values to slice of tensor object?

### ISSUE THREAD

**Issue by shoaib6174** [shoaib6174/GSOC-22-Video-Swin-Transformers#3]
@sayakpaul  @gustheman 

I am facing some issumes in the compute_mask() [Code](https://github.com/shoaib6174/GSOC-22-Video-Swin-Transformers/blob/main/VideoSwinTransformer/BasicLayer.py#L30)

I want to implement the code in the following way-

```python
import tensorflow as tf


# following values are passed in the function from basic_layer
window_size = (2,7,7)
shift_size = (0,3,3)
D, H, W = 2, 14 , 14 


img_mask = tf.zeros((1, D, H, W, 1))  

cnt = tf.Variable(0, dtype= "float32")

for d in slice(-window_size[0]), slice(-window_size[0], -shift_size[0]), slice(-shift_size[0],None):
    for h in slice(-window_size[1]), slice(-window_size[1], -shift_size[1]), slice(-shift_size[1],None):
        for w in slice(-window_size[2]), slice(-window_size[2], -shift_size[2]), slice(-shift_size[2],None):
            img_mask[:, d, h, w, :] = cnt
            cnt = cnt + 1
```

It gives the following error-

```
TypeError                                 Traceback (most recent call last)
<ipython-input-6-d74222409084> in <module>()
     11     for h in slice(-window_size[1]), slice(-window_size[1], -shift_size[1]), slice(-shift_size[1],None):
     12         for w in slice(-window_size[2]), slice(-window_size[2], -shift_size[2]), slice(-shift_size[2],None):
---> 13             img_mask[:, d, h, w, :] = cnt
     14             cnt = cnt + 1

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

```

Using np.zeros() instead of tf.zeros() runs the code successfully but it gives the following error while s initializing the model using tf.keras.Input() or saving the model-

```
TypeError: in user code:

    C:\Python\Python396\lib\site-packages\keras\saving\saving_utils.py:125 _wrapped_model  *
        outputs = model(*args, **kwargs)
    C:\Users\shoai\Codes\GSOC-22-Video-Swin-Transformers\VideoSwinTransformer\SwinTransformer3D.py:117 call  *
        x = layer(x)
    C:\Users\shoai\Codes\GSOC-22-Video-Swin-Transformers\VideoSwinTransformer\BasicLayer.py:169 call  *
        attn_mask = compute_mask(Dp.ref(), Hp.ref(), Wp.ref(), window_size, shift_size, None) #??
    C:\Users\shoai\Codes\GSOC-22-Video-Swin-Transformers\VideoSwinTransformer\BasicLayer.py:30 compute_mask  **
        img_mask = np.zeros((1, D, H, W, 1))

    TypeError: 'Tensor' object cannot be interpreted as an integer

```

This error occurs in the later case as D, H, W and elements of window_size & shift_size are passed into the function as Tensor object. 

np.zeors() can not take Tensor object as input. So it has to be implemented using tf.zeros().

Now I need a way to assign values to slice of tensor object (img_mask). 

Would you please suggest me how can I do the following assignment successully -

```pyhthon
img_mask[:, d, h, w, :] = cnt
```

**Comment by sayakpaul** [comment]
See how I am using a similar function here:

https://github.com/sayakpaul/swin-transformers-tf/blob/7a9be0c788e9ed0f2115d4744b302c2a1c8aac90/swins/blocks/swin_transformer_block.py#L98

I am pre-computing the attention masks and then initializing them so that `numpy` operations don't interfere with the TF graph:

https://github.com/sayakpaul/swin-transformers-tf/blob/7a9be0c788e9ed0f2115d4744b302c2a1c8aac90/swins/blocks/swin_transformer_block.py#L91

**Comment by sayakpaul** [comment]
Also, I saw you're using PyTorch related stuff like `.device`. Please take care of those. 

I think you won't be able to achieve einsum with `einops` within TensorFlow as those operations will become incompatible. Try using TensorFlow's einsum ops: https://www.tensorflow.org/api_docs/python/tf/einsum.

**Comment by shoaib6174** [comment]
> See how I am using a similar function here:
> 
> https://github.com/sayakpaul/swin-transformers-tf/blob/7a9be0c788e9ed0f2115d4744b302c2a1c8aac90/swins/blocks/swin_transformer_block.py#L98
> 
> I am pre-computing the attention masks and then initializing them so that `numpy` operations don't interfere with the TF graph:
> 
> https://github.com/sayakpaul/swin-transformers-tf/blob/7a9be0c788e9ed0f2115d4744b302c2a1c8aac90/swins/blocks/swin_transformer_block.py#L91

@sayakpaul  , I couldn't find a way to pre-compute the mask. 

In the implementation of the PyTorch version of the Swin Transformer, the attention mask is also pre-calculated while initializing the SwinTransformerBlock like yours. Link-
https://github.com/microsoft/Swin-Transformer/blob/main/models/swin_transformer.py#L223


But in the PyTorch implementation of Video Swin Transformer [get_window_size ](https://github.com/SwinTransformer/Video-Swin-Transformer/blob/master/mmaction/models/backbones/swin_transformer.py#71) function is called from the forward call of each BasicLayer. get_window_size returns  window_size and shift_size which are then used in [compute_mask](https://github.com/SwinTransformer/Video-Swin-Transformer/blob/master/mmaction/models/backbones/swin_transformer.py#L317) function.

Link-
https://github.com/SwinTransformer/Video-Swin-Transformer/blob/master/mmaction/models/backbones/swin_transformer.py#L400

This mask is computed at each of the BasicLayer and the same value is passed to all layers of SwinTransformerBlock3D of a BasicLayer.


Would you please give me some instructions on how I can pre-compute the mask or suggest any other way of implementing masking?

**Comment by shoaib6174** [comment]
> einsum

@sayakpaul  I haven't used einsum with einops. I have used einops's rearrange function. 

In my code:
https://github.com/shoaib6174/GSOC-22-Video-Swin-Transformers/blob/main/VideoSwinTransformer/SwinTransformer3D.py#L119

PyTorch ref:
https://github.com/SwinTransformer/Video-Swin-Transformer/blob/master/mmaction/models/backbones/swin_transformer.py#L659

The documentation of einops states that it supports both PyTorch and TF. 

Should I implement the rearrange function using tf.reshape or something else?

**Comment by sayakpaul** [comment]
https://github.com/shoaib6174/GSOC-22-Video-Swin-Transformers/issues/3#issuecomment-1204405744

If `einops` works, I don't mind keeping it. But try doing it with native TensorFlow to see if it's possible to discard the dependence on `einops`. 

Regarding precomputing masks, I think the resolution of the frames stays the same throughout training, right? If that's the case why can't we precompute the mask?

**Comment by shoaib6174** [comment]
> [#3 (comment)](https://github.com/shoaib6174/GSOC-22-Video-Swin-Transformers/issues/3#issuecomment-1204405744)
> 
> If `einops` works, I don't mind keeping it. But try doing it with native TensorFlow to see if it's possible to discard the dependence on `einops`.
> 
> Regarding precomputing masks, I think the resolution of the frames stays the same throughout training, right? If that's the case why can't we precompute the mask?

The resolution of the frames changes at each basic layer depending on the resolution of the input image. But I think pre-computing the mask will be possible if I provide the image_size as a parameter to the SwinTransformer3D while initializing. 

The SwinTransformer takes [image_size ](https://github.com/microsoft/Swin-Transformer/blob/main/models/swin_transformer.py#491)as a parameter  but The [SwinTransformer3D](https://github.com/SwinTransformer/Video-Swin-Transformer/blob/master/mmaction/models/backbones/swin_transformer.py#L459) does not. 

Thank you for the hint @sayakpaul .

I am trying this.

**Comment by shoaib6174** [comment]
@sayakpaul 
I have successfully pre-compute the mask after passing the input shape as a parameter. I also used this parameter in padding and Patch Merging. Thank you for the suggestion.

**Comment by sayakpaul** [comment]
Amazing!
